"""Unit tests of ``orthostudio.airports`` on a synthetic ``apt.dat`` (spec
``airports-index.md`` 7)."""

from __future__ import annotations

import os
import sqlite3
from pathlib import Path

import pytest

from orthostudio.airports import (
    AirportIndex,
    default_index,
    default_index_path,
    haversine_km,
    parse_apt_dat,
    tiles_within,
)
from orthostudio.errors import OsxpError
from orthostudio.model import TileRef

# Eight records: BOM + CRLF, a datum airport, an icao_code override, a runway fallback, a
# heliport with a 102 fallback, a seaplane base with a 101 fallback, an accentuated name, a
# record without any geometry, a duplicate header identifier, and a shared ICAO code.
_APT = (
    "﻿A\r\n"
    "1200 Generated by hand\r\n"
    "\r\n"
    "1     74 0 0 LFML Marseille Provence\r\n"
    "1302 city Marseille\r\n"
    "1302 datum_lat 43.436666667\r\n"
    "1302 datum_lon 5.215\r\n"
    "1302 icao_code LFML\r\n"
    "100 45.11 1 0 0.00 0 0 0 13L 43.4300 5.2100 0 0 1 0 0 0 31R 43.4500 5.2300 0 0 1 0 0 0\r\n"
    "\r\n"
    "1     50 0 0 XPA000C Manokotak\r\n"
    "1302 icao_code PAMB\r\n"
    "1302 datum_lat 58.932055556\r\n"
    "1302 datum_lon -158.901888889\r\n"
    "\r\n"
    "1     51 0 0 PAMB [X] Manokotak\r\n"
    "100 30.00 1 0 0.00 0 0 0 03 58.9800 -159.0600 0 0 1 0 0 0 21 58.9900 -159.0500 0 0 1 0 0 0\r\n"
    "\r\n"
    "1   1625 0 0 5TE Tetlin\r\n"
    "1302 local_code 5TE\r\n"
    "100 7.62 3 0 0.25 0 0 0  14 63.1361123 -142.5229183 0 0 1 0 0 0"
    " 32 63.1315349 -142.5209494 0 0 1 0 0 0\r\n"
    "19 63.1361990 -142.5227268 1\r\n"
    "\r\n"
    "17      0 0 0 ENQA [H] Troll A Platform\r\n"
    "1302 icao_code ENQA\r\n"
    "102 H1 60.6450000 3.7247220 0.0 12.00 12.00 15 0 0 0.00 0\r\n"
    "102 H2 60.6443023 3.7253884 0.0 12.00 12.00 15 0 0 0.00 0\r\n"
    "\r\n"
    "16      0 0 0 ENRM Rørvik Ryum\r\n"
    "1302 city Rørvik\r\n"
    "1302 state Provence-Alpes-Côte-d'Azur\r\n"
    "101 30.00 0 08 64.8400 11.1400 26 64.8360 11.1520\r\n"
    "\r\n"
    "1      0 0 0 NOGEO Nowhere\r\n"
    "1302 city Limbo\r\n"
    "\r\n"
    "1     10 0 0 LFML Second Marseille (duplicate identifier)\r\n"
    "1302 datum_lat 0.0\r\n"
    "1302 datum_lon 0.0\r\n"
    "\r\n"
    "99\r\n"
)


@pytest.fixture
def apt_dat(tmp_path: Path) -> Path:
    p = tmp_path / "apt.dat"
    p.write_bytes(_APT.encode("utf-8"))
    return p


@pytest.fixture
def index(tmp_path: Path, apt_dat: Path) -> AirportIndex:
    idx = AirportIndex(tmp_path / "airports.sqlite")
    idx.build(apt_dat)
    return idx


# ---------------------------------------------------------------- parsing


def test_parse_streams_every_record_with_bom_and_crlf(apt_dat: Path) -> None:
    rows = list(parse_apt_dat(apt_dat))
    idents = [r[1] for r in rows]
    # NOGEO is dropped (no geometry); the duplicate LFML is yielded (sqlite resolves it).
    assert idents == ["LFML", "XPA000C", "PAMB", "5TE", "ENQA", "ENRM", "LFML"]


def test_parse_small_block_boundaries(apt_dat: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    import orthostudio.airports as mod

    monkeypatch.setattr(mod, "BLOCK_SIZE", 7)
    rows = list(parse_apt_dat(apt_dat))
    assert [r[1] for r in rows] == ["LFML", "XPA000C", "PAMB", "5TE", "ENQA", "ENRM", "LFML"]


def test_parse_progress_callback(apt_dat: Path) -> None:
    calls: list[tuple[int, int]] = []
    list(parse_apt_dat(apt_dat, progress=lambda d, t: calls.append((d, t))))
    total = apt_dat.stat().st_size
    assert calls[-1] == (total, total)
    assert all(0 <= d <= t == total for d, t in calls)


def test_build_stats(index: AirportIndex, apt_dat: Path) -> None:
    stats = index.build(apt_dat)
    assert stats.airports == 6
    assert (stats.land, stats.sea, stats.heli) == (4, 1, 1)
    # Parser counters count records, not rows: the ignored duplicate LFML has a datum too.
    assert stats.with_datum == 3  # LFML, XPA000C, duplicate LFML
    assert stats.fallback_runway == 4  # PAMB, 5TE, ENQA (102), ENRM (101)
    assert stats.fallback_other == 0
    assert stats.skipped_no_position == 1  # NOGEO
    assert stats.duplicate_idents == 1  # second LFML
    assert stats.shared_icao == 1  # PAMB carried by XPA000C and by the closed PAMB
    assert stats.source_size == apt_dat.stat().st_size
    meta = index.stats()
    assert meta["schema_version"] == "1"
    assert meta["airports"] == "6"
    assert meta["source_path"] == str(apt_dat)


def test_datum_wins_over_runway(index: AirportIndex) -> None:
    a = index.get("LFML")
    assert a is not None
    assert (a.lat, a.lon) == pytest.approx((43.436666667, 5.215))
    assert a.has_datum and a.icao_explicit
    assert a.name == "Marseille Provence"
    assert a.elev_ft == 74
    assert a.kind == "land"
    assert a.tile == TileRef(43, 5)


def test_runway_midpoint_fallback(index: AirportIndex) -> None:
    a = index.get("5TE")
    assert a is not None
    assert not a.has_datum and not a.icao_explicit
    assert a.lat == pytest.approx(63.1361123)
    assert a.lon == pytest.approx(-142.5229183)
    assert a.elev_ft == 1625


def test_helipad_and_water_runway_fallbacks(index: AirportIndex) -> None:
    heli = index.get("ENQA")
    assert heli is not None and heli.kind == "heli"
    assert (heli.lat, heli.lon) == pytest.approx((60.645, 3.724722))
    sea = index.get("ENRM")
    assert sea is not None and sea.kind == "sea"
    assert (sea.lat, sea.lon) == pytest.approx((64.84, 11.14))
    assert sea.name == "Rørvik Ryum"


def test_record_without_geometry_is_dropped(index: AirportIndex) -> None:
    assert index.get("NOGEO") is None


def test_duplicate_identifier_keeps_the_first(index: AirportIndex) -> None:
    a = index.get("LFML")
    assert a is not None and a.name == "Marseille Provence"
    assert index.count() == 6


def test_shared_icao_prefers_explicit_icao_code(index: AirportIndex) -> None:
    a = index.get("PAMB")
    assert a is not None
    assert a.ident == "XPA000C" and a.name == "Manokotak"
    closed = index.get("XPA000C")
    assert closed is not None and closed.ident == "XPA000C"
    # The closed airport is still reachable by its header identifier through search.
    names = {x.name for x in index.search("PAMB")}
    assert names == {"Manokotak", "[X] Manokotak"}


# ---------------------------------------------------------------- search


def test_search_prefix_case_insensitive(index: AirportIndex) -> None:
    assert [a.icao for a in index.search("lfm")] == ["LFML"]
    # Identifier prefixes rank before a name substring ("Marseille Prov*en*ce").
    assert [a.icao for a in index.search("EN")] == ["ENQA", "ENRM", "LFML"]
    assert [a.icao for a in index.search("EN", kinds=["heli", "sea"])] == ["ENQA", "ENRM"]


def test_search_name_substring(index: AirportIndex) -> None:
    assert [a.icao for a in index.search("marseille")] == ["LFML"]
    assert [a.icao for a in index.search("Troll")] == ["ENQA"]
    assert [a.icao for a in index.search("ørvik")] == ["ENRM"]


def test_search_ranking_exact_then_prefix_then_name(tmp_path: Path) -> None:
    apt = tmp_path / "apt.dat"
    apt.write_text(
        "A\n1200\n"
        "1 0 0 0 LFM Lfml lookalike\n1302 datum_lat 1\n1302 datum_lon 1\n"
        "1 0 0 0 LFMN Nice\n1302 datum_lat 2\n1302 datum_lon 2\n"
        "1 0 0 0 ZZZZ Contains lfm in name\n1302 datum_lat 3\n1302 datum_lon 3\n"
        "99\n",
        encoding="utf-8",
    )
    idx = AirportIndex(tmp_path / "db.sqlite")
    idx.build(apt)
    assert [a.icao for a in idx.search("LFM")] == ["LFM", "LFMN", "ZZZZ"]


def test_search_limit_empty_and_kinds(index: AirportIndex) -> None:
    assert index.search("") == []
    assert index.search("   ") == []
    assert index.search("E", limit=0) == []
    assert len(index.search("E", limit=1)) == 1
    assert [a.icao for a in index.search("EN", kinds=["heli"])] == ["ENQA"]
    assert index.search("EN", kinds=[]) == []


def test_get_unknown_and_blank(index: AirportIndex) -> None:
    assert index.get("XXXX") is None
    assert index.get("") is None


def test_queries_on_missing_db(tmp_path: Path) -> None:
    idx = AirportIndex(tmp_path / "none.sqlite")
    assert idx.search("LF") == []
    assert idx.get("LFML") is None
    assert idx.count() == 0
    assert idx.stats() == {}
    with pytest.raises(KeyError):
        idx.tiles_around("LFML", 10)


# ---------------------------------------------------------------- tiles


def test_tiles_around_radius_zero(index: AirportIndex) -> None:
    assert index.tiles_around("LFML", 0) == [TileRef(43, 5)]


def test_tiles_around_30km_marseille(index: AirportIndex) -> None:
    tiles = index.tiles_around("lfml", 30)
    assert TileRef(43, 5) in tiles
    assert TileRef(43, 4) in tiles  # the west edge at lon 5 is 17 km away
    assert TileRef(42, 5) not in tiles  # the south edge at lat 43 is 49 km away


def test_tiles_around_unknown_raises(index: AirportIndex) -> None:
    with pytest.raises(KeyError):
        index.tiles_around("XXXX", 10)


def test_tiles_within_corner_gives_four_tiles() -> None:
    assert tiles_within(43.0001, 5.0001, 1.0) == [
        TileRef(42, 4),
        TileRef(42, 5),
        TileRef(43, 4),
        TileRef(43, 5),
    ]


def test_tiles_within_antimeridian_wraps() -> None:
    tiles = tiles_within(0.5, 179.9, 30.0)
    assert tiles == [TileRef(0, -180), TileRef(0, 179)]
    tiles = tiles_within(0.5, -179.9, 30.0)
    assert tiles == [TileRef(0, -180), TileRef(0, 179)]


def test_tiles_within_large_radius_spans_latitude() -> None:
    tiles = tiles_within(43.5, 5.5, 150.0)
    lats = {t.lat for t in tiles}
    assert lats == {42, 43, 44}
    assert TileRef(42, 5) in tiles and TileRef(44, 5) in tiles
    assert TileRef(43, 3) in tiles and TileRef(43, 7) in tiles


def test_tiles_within_poles_and_negative_radius() -> None:
    assert TileRef(89, 0) in tiles_within(89.9, 0.3, 5.0)
    assert all(t.lat <= 89 for t in tiles_within(89.9, 0.3, 500.0))
    assert all(t.lat >= -90 for t in tiles_within(-89.9, 0.3, 500.0))
    with pytest.raises(ValueError):
        tiles_within(0, 0, -1)


def test_haversine_reference() -> None:
    # Marseille -> Nice, about 158 km.
    assert haversine_km(43.4367, 5.215, 43.6584, 7.2159) == pytest.approx(163.0, abs=2.0)
    assert haversine_km(10, 10, 10, 10) == 0.0


# ---------------------------------------------------------------- staleness, atomicity


def test_is_stale_and_ensure(index: AirportIndex, apt_dat: Path) -> None:
    assert not index.is_stale(apt_dat)
    assert index.ensure(apt_dat) is None
    st = apt_dat.stat()
    os.utime(apt_dat, ns=(st.st_atime_ns, st.st_mtime_ns + 1_000_000_000))
    assert index.is_stale(apt_dat)
    stats = index.ensure(apt_dat)
    assert stats is not None and stats.airports == 6
    assert not index.is_stale(apt_dat)
    assert index.is_stale(apt_dat.with_name("missing.dat"))


def test_schema_version_mismatch_is_stale(index: AirportIndex, apt_dat: Path) -> None:
    with sqlite3.connect(index.db) as con:
        con.execute("UPDATE meta SET v = '0' WHERE k = 'schema_version'")
    assert index.is_stale(apt_dat)


def test_build_is_atomic_and_cleans_tmp(tmp_path: Path, apt_dat: Path) -> None:
    idx = AirportIndex(tmp_path / "airports.sqlite")
    idx.build(apt_dat)
    before = idx.db.read_bytes()
    with pytest.raises(FileNotFoundError):
        idx.build(tmp_path / "absent.dat")
    assert idx.db.read_bytes() == before
    assert not idx.db.with_name("airports.sqlite.tmp").exists()
    assert idx.get("LFML") is not None


def test_build_creates_parent_dirs(tmp_path: Path, apt_dat: Path) -> None:
    idx = AirportIndex(tmp_path / "deep" / "er" / "airports.sqlite")
    idx.build(apt_dat)
    assert idx.count() == 6


def test_corrupt_db_is_stale(tmp_path: Path, apt_dat: Path) -> None:
    idx = AirportIndex(tmp_path / "airports.sqlite")
    idx.db.write_bytes(b"not a database")
    assert idx.is_stale(apt_dat)
    idx.build(apt_dat)
    assert idx.count() == 6


# ---------------------------------------------------------------- default_index


def _fake_xplane(root: Path, apt_text: str) -> Path:
    xp = root / "X-Plane 12"
    (xp / "Resources").mkdir(parents=True)
    (xp / "Custom Scenery").mkdir()
    nav = xp / "Global Scenery" / "Global Airports" / "Earth nav data"
    nav.mkdir(parents=True)
    (nav / "apt.dat").write_text(apt_text, encoding="utf-8")
    return xp


def test_default_index_builds_under_osxp_home(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("OSXP_HOME", str(tmp_path / "home"))
    xp = _fake_xplane(tmp_path, _APT)
    seen: list[tuple[int, int]] = []
    idx = default_index(xp, progress=lambda d, t: seen.append((d, t)))
    assert idx.db == tmp_path / "home" / "airports.sqlite" == default_index_path()
    assert idx.db.exists() and seen
    assert idx.get("LFML") is not None
    # Fresh: no rebuild, no progress.
    seen.clear()
    default_index(xp, progress=lambda d, t: seen.append((d, t)))
    assert seen == []


def test_default_index_errors(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OSXP_HOME", str(tmp_path / "home"))
    with pytest.raises(OsxpError) as exc:
        default_index(tmp_path / "nope")
    assert exc.value.code == "XP_DIR_NOT_FOUND"
    xp = tmp_path / "X-Plane 12"
    (xp / "Resources").mkdir(parents=True)
    (xp / "Custom Scenery").mkdir()
    with pytest.raises(OsxpError) as exc:
        default_index(xp)
    assert exc.value.code == "XP_GLOBAL_SCENERY_NOT_FOUND"


def test_default_index_none_uses_detection(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    import orthostudio.airports as mod

    monkeypatch.setenv("OSXP_HOME", str(tmp_path / "home"))
    monkeypatch.setattr(mod, "detect_xplane", lambda: None)
    with pytest.raises(OsxpError) as exc:
        default_index(None)
    assert exc.value.code == "XP_DIR_NOT_FOUND"
    xp = _fake_xplane(tmp_path, _APT)
    monkeypatch.setattr(mod, "detect_xplane", lambda: xp)
    assert default_index(None).get("ENQA") is not None
