"""Tests for orthostudio.mesh.triangle_io: synthetic round trips."""

from __future__ import annotations

import math
import os
import subprocess
from pathlib import Path

import numpy as np
import pytest

from orthostudio.mesh import triangle_io as tio

pytestmark = pytest.mark.usefixtures("number_parsing")

REPO = Path(__file__).resolve().parents[1]
OSXP_TRIANGLE4XP = Path(
    os.environ.get("OSXP_TRIANGLE4XP", REPO / "native" / "triangle4xp" / "build" / "Triangle4XP")
)


# ------------------------------------------------------------------ synthetic fixtures


def _square_nodes(rng: np.random.Generator, n_inner: int = 20) -> tio.NodeTable:
    corners = np.array([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]])
    inner = rng.random((n_inner, 2))
    xy = np.vstack([corners, inner])
    alt = rng.random(len(xy)) * 1000.0
    return tio.NodeTable(points=np.column_stack([xy, alt]), first_number=1)


def _square_pslg(nodes: tio.NodeTable) -> tio.Pslg:
    segments = np.array([[1, 2], [2, 3], [3, 4], [4, 1]], dtype=np.int32)
    markers = np.array([0, 0, 1, 1], dtype=np.int32)
    regions = np.array([[0.5, 0.5, 1.0, 1.0]])
    return tio.Pslg(
        segments=segments,
        segment_markers=markers,
        holes=np.zeros((0, 2)),
        regions=regions,
        nodes=None,
        first_number=nodes.first_number,
    )


def _write_text_node(path: Path, nodes: tio.NodeTable) -> None:
    with open(path, "w") as f:
        n_markers = 0 if nodes.markers is None else 1
        f.write(f"{nodes.n_vertices} 2 {nodes.n_attrs} {n_markers}\n")
        for i, row in enumerate(nodes.points):
            fields = [str(i + nodes.first_number)] + [f"{v:.17g}" for v in row]
            if nodes.markers is not None:
                fields.append(str(int(nodes.markers[i])))
            f.write(" ".join(fields) + "\n")
        f.write("# Generated by a test\n")


def _write_text_poly(path: Path, pslg: tio.Pslg) -> None:
    with open(path, "w") as f:
        f.write("0 2 1 0\n\n")
        n_markers = 0 if pslg.segment_markers is None else 1
        f.write(f"{pslg.n_segments} {n_markers}\n")
        for i, (a, b) in enumerate(pslg.segments):
            line = f"{i + 1} {a} {b}"
            if pslg.segment_markers is not None:
                line += f" {int(pslg.segment_markers[i])}"
            f.write(line + "\n")
        holes = pslg.holes if pslg.holes is not None else np.zeros((0, 2))
        f.write(f"\n{len(holes)}\n")
        for i, (x, y) in enumerate(holes):
            f.write(f"{i + 1} {x:.15f} {y:.15f}\n")
        regions = pslg.regions if pslg.regions is not None else np.zeros((0, 4))
        f.write(f"\n{len(regions)}\n")
        for i, (x, y, attr, _area) in enumerate(regions):
            f.write(f"{i + 1} {x:.15f} {y:.15f} {int(attr)}\n")  # Ortho4XP omits max_area


# --------------------------------------------------------------------- unit tests


def test_node_binary_round_trip(tmp_path: Path) -> None:
    rng = np.random.default_rng(1)
    nodes = _square_nodes(rng)
    markers = rng.integers(0, 3, nodes.n_vertices).astype(np.int32)
    nodes = tio.NodeTable(points=nodes.points, markers=markers, first_number=0)
    tio.write_node_binary(tmp_path / "a.node", nodes)
    back = tio.read_node_binary(tmp_path / "a.node")
    assert np.array_equal(back.points, nodes.points)
    assert back.markers is not None and np.array_equal(back.markers, markers)
    assert back.first_number == 0
    assert back.n_attrs == 1
    assert tio.read_node(tmp_path / "a.node").n_vertices == nodes.n_vertices


def test_poly_binary_round_trip(tmp_path: Path) -> None:
    rng = np.random.default_rng(2)
    nodes = _square_nodes(rng)
    pslg = _square_pslg(nodes)
    tio.write_poly_binary(tmp_path / "a.poly", pslg)
    back = tio.read_poly_binary(tmp_path / "a.poly")
    assert back.nodes is None
    assert np.array_equal(back.segments, pslg.segments)
    assert back.segment_markers is not None
    assert np.array_equal(back.segment_markers, pslg.segment_markers)
    assert back.holes is not None and back.holes.shape == (0, 2)
    assert back.regions is not None and np.array_equal(back.regions, pslg.regions)
    # embedded vertices
    embedded = tio.Pslg(segments=pslg.segments, nodes=nodes)
    tio.write_poly_binary(tmp_path / "b.poly", embedded)
    back = tio.read_poly_binary(tmp_path / "b.poly")
    assert back.nodes is not None and np.array_equal(back.nodes.points, nodes.points)
    assert back.segment_markers is None and back.regions is not None
    assert back.regions.shape == (0, 4)


def test_ele_binary_round_trip(tmp_path: Path) -> None:
    tris = np.array([[1, 2, 3], [1, 3, 4]], dtype=np.int32)
    attrs = np.array([[0.0], [128.0]])
    tio.write_ele_binary(tmp_path / "a.ele", tio.Elements(tris, attrs, first_number=1))
    back = tio.read_ele(tmp_path / "a.ele")
    assert np.array_equal(back.triangles, tris) and np.array_equal(back.attributes, attrs)
    assert back.first_number == 1 and back.n_attrs == 1


def test_text_readers_match_binary(tmp_path: Path) -> None:
    rng = np.random.default_rng(3)
    nodes = _square_nodes(rng)
    pslg = _square_pslg(nodes)
    _write_text_node(tmp_path / "t.node", nodes)
    _write_text_poly(tmp_path / "t.poly", pslg)
    tn = tio.read_node_text(tmp_path / "t.node")
    assert np.array_equal(tn.points, nodes.points)  # %.17g round-trips doubles exactly
    assert tn.markers is None and tn.first_number == 1
    tp = tio.read_poly(tmp_path / "t.poly")
    assert np.array_equal(tp.segments, pslg.segments)
    assert tp.segment_markers is not None
    assert np.array_equal(tp.segment_markers, pslg.segment_markers)
    assert tp.regions is not None
    # missing max_area column: Triangle copies the attribute, so does the reader
    assert np.array_equal(tp.regions, pslg.regions)


def test_text_ele_reader(tmp_path: Path) -> None:
    text = "2  3  1\n   1    1  2  3  0\n   2    1  3  4  128\n# Generated by\n"
    (tmp_path / "t.ele").write_text(text)
    ele = tio.read_ele_text(tmp_path / "t.ele")
    assert ele.triangles.tolist() == [[1, 2, 3], [1, 3, 4]]
    assert ele.attributes.tolist() == [[0.0], [128.0]]


def test_bad_magic_and_truncation(tmp_path: Path) -> None:
    (tmp_path / "bad.node").write_bytes(b"OSXPELE1" + b"\0" * 20)
    with pytest.raises(tio.TriangleFormatError):
        tio.read_node_binary(tmp_path / "bad.node")
    rng = np.random.default_rng(4)
    nodes = _square_nodes(rng)
    tio.write_node_binary(tmp_path / "ok.node", nodes)
    data = (tmp_path / "ok.node").read_bytes()
    (tmp_path / "short.node").write_bytes(data[:-8])
    with pytest.raises(tio.TriangleFormatError):
        tio.read_node_binary(tmp_path / "short.node")


def test_invalid_shapes_rejected() -> None:
    with pytest.raises(tio.TriangleFormatError):
        tio.NodeTable(points=np.zeros((3,)))
    with pytest.raises(tio.TriangleFormatError):
        tio.Pslg(segments=np.zeros((3, 3), dtype=np.int32))
    with pytest.raises(tio.TriangleFormatError):
        tio.Elements(triangles=np.zeros((2, 4), dtype=np.int32), attributes=np.zeros((2, 0)))


# ------------------------------------------------------------- sidecar (built binary)

needs_binary = pytest.mark.skipif(
    not OSXP_TRIANGLE4XP.is_file(), reason="Triangle4XP not built (native/triangle4xp/build)"
)

# DEM window used for the synthetic square: 11 x 11 samples over [-0.01, 1.01]^2, flat.
_SYNTH_DEM = dict(nx=11, ny=11, x0=-0.01, y0=-0.01, x1=1.01, y1=1.01, nodata=-32768.0)


def _triangle_args(
    switches: str, alt: Path, weight: Path, poly: Path, dem: dict, lat: float = 43.0
) -> list[str]:
    lat_to_m = math.pi * 6378137 / 180
    return [
        str(OSXP_TRIANGLE4XP),
        switches,
        f"{lat_to_m * math.cos(math.pi * lat / 180):.9g}",
        f"{lat_to_m:.9g}",
        str(dem["nx"]),
        str(dem["ny"]),
        f"{dem['x0']:.9g}",
        f"{dem['y0']:.9g}",
        f"{dem['x1']:.9g}",
        f"{dem['y1']:.9g}",
        f"{dem['nodata']:.9g}",
        "2",
        str(alt),
        str(weight),
        str(poly),
    ]


def _run(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, capture_output=True, text=True, check=False)


@needs_binary
def test_sidecar_text_and_binary_modes_agree(tmp_path: Path) -> None:
    rng = np.random.default_rng(5)
    nodes = _square_nodes(rng, n_inner=50)
    pslg = _square_pslg(nodes)
    alt = tmp_path / "s.alt"
    weight = tmp_path / "s.weight"
    (rng.random((11, 11)) * 100).astype(np.float32).tofile(alt)
    np.ones((1001, 1001), dtype=np.float32).tofile(weight)
    text_dir = tmp_path / "text"
    bin_dir = tmp_path / "bin"
    text_dir.mkdir()
    bin_dir.mkdir()
    _write_text_node(text_dir / "s.node", nodes)
    _write_text_poly(text_dir / "s.poly", pslg)
    tio.write_node_binary(bin_dir / "s.node", nodes)
    tio.write_poly_binary(bin_dir / "s.poly", pslg)
    switches = "-pq10AuYBQPS500000"
    res = _run(_triangle_args(switches, alt, weight, text_dir / "s.poly", _SYNTH_DEM))
    assert res.returncode == 0, res.stdout
    res = _run(_triangle_args("-pq10AuYBQPbS500000", alt, weight, bin_dir / "s.poly", _SYNTH_DEM))
    assert res.returncode == 0, res.stdout
    tn = tio.read_node_text(text_dir / "s.1.node")
    bn = tio.read_node_binary(bin_dir / "s.1.node")
    te = tio.read_ele_text(text_dir / "s.1.ele")
    be = tio.read_ele_binary(bin_dir / "s.1.ele")
    assert bn.n_attrs == tn.n_attrs == 4  # z, u, v + the input altitude attribute
    assert np.array_equal(tn.points, bn.points)
    assert tn.markers is None and bn.markers is None  # -B
    assert np.array_equal(te.triangles, be.triangles)
    assert np.array_equal(te.attributes, be.attributes)
    assert be.n_triangles > 50 and set(np.unique(be.attributes)) <= {0.0, 1.0}


@needs_binary
def test_sidecar_rejects_binary_with_refine(tmp_path: Path) -> None:
    dem = dict(nx=3, ny=3, x0=0.0, y0=0.0, x1=1.0, y1=1.0, nodata=-1.0)
    alt, weight, node = (tmp_path / n for n in ("a.alt", "a.weight", "x.node"))
    args = _triangle_args("-rb", alt, weight, node, dem)
    res = _run(args)  # rejected while parsing the command line, before any file is opened
    assert res.returncode != 0
    assert "-b" in res.stdout and "-r" in res.stdout
